### ISSUE TITLE
[enhancement][openstack] abstrackt usage of image_id to ref or id

### ISSUE THREAD

**Issue by epcim** [chef/chef-provisioning-fog#104]
example for openstack:
instead of populating image_ref/flavor_ref/key_name with ID or Full URL (as specified here: ) provide a way to populate chef-configuration with a image refference which = image name in os.

instead of:
```
  :image_ref => '783a1ca1-6310-4187-bfe1-21a6213ef956',
  :flavor_ref => '7c438087-10d7-4688-ac01-48614c2af3ff'

```

do:
```
  :image_ref => ubuntu-trusty,
  :flavor_ref => m1.small
```

**Comment by bdangit** [comment]
this might be hard to achieve as I'm sure the image_ids are different across Openstack implementations. unless there is already an attribute that allows you to specify the "name".

**Comment by maxlinc** [comment]
You just find by name. Lots of projects do this already, for example see this PR to knife-openstack:
https://github.com/chef/knife-openstack/pull/120

**Comment by jjasghar** [comment]
@maxlinc thanks for this, yeah, to what @bdangit says this would be pretty hard in general. Going to close this.
