### ISSUE TITLE
[openstack] timeout calculation

### ISSUE THREAD

**Issue by epcim** [chef/chef-provisioning-fog#106]
I am sorry if I am not correct, I am not a everyday rubyist. We store `'starded_at'` as `Time.now.to_i` but later we subtract from `Time.now.utc` assuming local time is in UTC as well.

https://github.com/chef/chef-provisioning-fog/blob/ebd78fae4b4582c5abd284b1cbe9954e425f2eda/lib/chef/provisioning/fog_driver/driver.rb#L212

http://ruby-doc.org/stdlib-2.1.1/libdoc/time/rdoc/Time.html

**Comment by randomcamel** [comment]
This is a clearer example, and does indeed look like it's wrong.

    https://github.com/chef/chef-provisioning-fog/blob/ebd78fae4b4582c5abd284b1cbe9954e425f2eda/lib/chef/provisioning/fog_driver/driver.rb#L372

**Comment by jjasghar** [comment]
I'll get this PR in ASAP. this seems like pretty easy fix.

**Comment by jjasghar** [comment]
fix https://github.com/chef/chef-provisioning-fog/pull/133
