### ISSUE TITLE
Bootstrapping requires node to have internet access

### ISSUE THREAD

**Issue by bbgobie** [chef/chef-provisioning-fog#122]
Currently boostrapping requires that the node have internet access to install the client.
Would be nice to automatically check, and if it doesn't, push the client from the machine doing the provisioning, or provide a resource for it like a local artifactory.

**Comment by jjasghar** [comment]
Interesting. I like this idea, but this seems like something on the `chef-provisioning` side, not the `chef-provisioning-fog` driver. Maybe you can [open an issue](https://github.com/chef/chef-provisioning/issues) on `chef-provisioning`? Please close this if you're ok with that.
