### ISSUE TITLE
Rackspace - support for RackConnect

### ISSUE THREAD

**Issue by djoos** [chef/chef-provisioning-fog#124]
Hi there,

it would be amazing to get support for RackConnect in the driver as currently our machine creates are interrupted when RackConnect "kicks in" and changes the public IP of the machine...

knife-rackspace supports [RackConnect v2](https://github.com/chef/knife-rackspace/blob/master/README.rdoc#knife-and-rackconnect-version-2) and [RackConnect v3](https://github.com/chef/knife-rackspace/blob/master/README.rdoc#knife-and-rackconnect-version-3) - perhaps something similar could be implemented?

Thanks in advance!

Kind regards,
David

**Comment by djoos** [comment]
FYI: here's knife-rackspace's [work-around](https://github.com/chef/knife-rackspace/pull/42/files) for the RackConnect issue.

**Comment by djoos** [comment]
Ok, so: I've tried to make use of the transport_address_location => :private_ip  (+ deprecated use_private_ip_for_ssh => true) to get round the RackConnect public IP change, but this didn't work either...

Thanks in advance for your feedback!

Kind regards,
David

**Comment by jjasghar** [comment]
@martinb3 can you help out here? I'm not too well versed with RackConnect.

**Comment by martinb3** [comment]
@djoos can you let us know if you're using RackConnect v2 or v3? It seems like it would be better to add this functionality into fog than maintain it in knife-rackspace, kitchen-rackspace, chef-provisioning-fog, etc. Just reading https://github.com/fog/fog/issues/1507 though, it seems like it's a tricky problem for fog as well, since it requires knowledge of not just Compute APIs but also some of the auth-related APIs. @mdarby, do you have any sense of the status of this in fog?

**Comment by djoos** [comment]
Hi @martinb3,

sure: we're making use of RackConnect v2.

Thanks in advance!

Kind regards,
David

**Comment by mdarby** [comment]
RackconnectV3 is in the `rackconnect` gem and will likely not be pushed into fog proper. Rackconnect V2 status is off the radar as focus is on V3.

**Comment by martinb3** [comment]
@djoos It sounds like if the support isn't going to be in fog for RCv2, your best bet is probably to upgrade to the latest version when the time comes.

If the support isn't in fog, I don't think we're going to be able to do a whole lot to assist in chef-provisioning-fog. I'll keep poking around, and post any updates if I get them.

**Comment by djoos** [comment]
Thanks for the update!

Unfortunately there's no upgrade path from RackConnect v2 to v3 (yet), so there might well be some other people who will stumble upon this thread with a similar issue...

As a workaround we make use of the transport_address_location => :private_ip (+ deprecated use_private_ip_for_ssh => true) to get round the RackConnect public IP change. I mentioned that initially I thought that was not doing the trick, however it does seem to be doing the trick.

I'll close this issue now, thanks again for the information - have a great evening!
David
