### ISSUE TITLE
Simple example fails with :transport_options required [openstack]

### ISSUE THREAD

**Issue by epcim** [chef/chef-provisioning-fog#127]
I have had working chef-provisionig recipe, after an upgrade to lates chefdk it stoped working. Seems there were introduced `machine_options :transport_options` in recent chef-provisioning, which are not resolved in the "fog" providers (or at least openstack).

In general, transport_options are for SSH driver filled with info like:
```
 machine_options :transport_options => {
   'ip_address' => HOSTMAP['one.lab.ci']['ip'],
   'ssh_options' => SSH_OPTIONS,                            
   'username' => 'root'
 }
```

Well for openstack, when before `action :allocate` no machines might be running, these options cannot be properly populated.
```    ================================================================================
    Error executing action `converge` on resource 'machine_batch[default]'
    ================================================================================
    
    RuntimeError
    ------------
    Machine Options for one.lab.ci are invalid cannot create machine.
      :transport_options required.
    
    Resource Declaration:
    ---------------------
    # In /workspace-chef/chef-repo/recipes/provision_ci.rb
    
     49: machine_batch do
     53:   %w(one two three).each do |m|
     54:     machine "#{m}.lab.ci" do
     55:       action :allocate
     63:       add_machine_options bootstrap_options: PER_MACHINE_BOOTSTRAP_OPTIONS[m] || {}
     64:       retries 1
     65:     end
     66:   end
     67: end
     68: 
```

**Comment by jjasghar** [comment]
I'm going to attempt to repo this today 9/29.

**Comment by epcim** [comment]
taking back, my fault - as one of my rake overrides loaded a recipe loading `chef/provisioning/ssh_driver` together with `fog:openstack` driver.

Note: :transport_options comes from chef-provisioning-ssh driver, documented here - https://github.com/chef/chef-provisioning-ssh
