### ISSUE TITLE
Provider Linode

### ISSUE THREAD

**Issue by aberrios85** [chef/chef-provisioning-fog#128]
Anyone working on fog_driver/providers/linode.rb ? I'm probably going to start on it or if someone has something I'll contribute....

**Comment by jjasghar** [comment]
I don't think anyone has asked for it yet, but if you can it bootstrapped I can help you out too. We're trying to get examples on the README also now, so if you do get it working please add the needed information.

**Comment by jjasghar** [comment]
@aberrios85 any chance you've worked/made any progress on this?

**Comment by jjasghar** [comment]
pinging @aberrios85 to see if you've made any progress :+1:

**Comment by jjasghar** [comment]
No movement, if you'd like to help I'd love to see PR, but I'm closing this due to no support.
