### ISSUE TITLE
NameError: uninitialized constant Chef::Provisioning::FogDriver::Driver::Cheff

### ISSUE THREAD

**Issue by marek-knappe** [chef/chef-provisioning-fog#142]
https://github.com/chef/chef-provisioning-fog/commit/72915586b1343b09926fb9344ea9905646e84628
Look at my comment in the file, there is Cheff instead of Chef:log

**Comment by randomcamel** [comment]
Good catch. Just fixed it in master.

**Comment by randomcamel** [comment]
@marek-knappe FYI, just released 0.15.3 with this fix.
