### ISSUE TITLE
machine names do not appear to be idempotent

### ISSUE THREAD

**Issue by bdangit** [chef/chef-provisioning-fog#145]
If I have manually allocated a machine called "foo" and converge a chef recipe that has resource `machine 'foo'`, then I expect chef to know that my machine named "foo" exists from my cloud provider and understands that it needs to bootstrap it to Chef and do allthethings necessary to be managed by Chef. 

We are currently running into an issue where we have pre-allocated the machines but the Chef goes ahead allocates a new set of machines and we end up with duplicated named machines in our Cloud Provider. 

Maybe this already exists in other provisioning gems and is yet to be ported here.

**Comment by jjasghar** [comment]
@bdangit is this still an issue? If so please reopen this issue.
