### ISSUE TITLE
HOWTO or other doc for working with Fog-based providers (SoftLayer)

### ISSUE THREAD

**Issue by boldandbusted** [chef/chef-provisioning-fog#148]
Howdy. I'm new to Chef, but not new to systems administration, so I'm not dumb, but I am ignorant. ;) I've read through the docs here and in chef-provisioning, and some of the source code, but I'm having a hard time figuring out how to tie everything together to just make a machine on SoftLayer. Presently, SoftLayer seems to be the "red headed stepchild" in Chef Provisioning, but I'm happy to use this driver and Fog... if I could figure out how all the various parts fit together!

Does someone have a soup-to-nuts example of a recipe to create machines in SoftLayer with this driver? I'm unclear on where I would use 'fog_key_pair', how I can set driver options inside the recipe (via environment variables for the softlayer username and API key), what I set under 'machine_options' and what I set elsewhere, etc. Must I use knife.rb, or can I just pass environment variables to the recipe(s)?

Also, a "cheat sheet" for taking examples from other dedicated chef-provisioning drivers (chef-provisiong-aws, for example) and translating those into using this driver would rock! 

Thanks for your work. Totally happy to explain more, or, if possible, explain less. ;)

**Comment by jjasghar** [comment]
Hi @boldandbusted !

Luckily it looks like you have a [provider for Softlayer](https://github.com/chef/chef-provisioning-fog/blob/master/lib/chef/provisioning/fog_driver/providers/softlayer.rb) already. 

It you take a look at: https://github.com/jjasghar/chef-provisioning-fog-example you can see the difference between digital ocean and openstack.

I have no experience with Soflayer so i'm not sure if that's everything you need but at least it'll help get you on your path.

I'd love to see more support for the other providers in c-p-fog, we just need more of the community to hash these things out.

**Comment by jjasghar** [comment]
Oh! And I also have [this blog post](http://jjasghar.github.io/blog/2015/09/25/chef-provisioning-fog-step-by-step-day-by-day/) which might help too.

**Comment by boldandbusted** [comment]
@jjasghar Ah, yes, that post is one of my prime sources! ;) Thanks for publishing that. 

I'm not sure, just from looking at that SoftLayer provider code, what is "internal code" vs. what is exposed to me for use as a end-user of that code.

**Comment by jjasghar** [comment]
Yeah sorry, i'm not a great resource for this. I'll ask around, and maybe a post to the discourse.chef.io asking for people with softlayer experience might help drum up some interest.

I wish i could help more, but I just don't have exposure. :(

**Comment by boldandbusted** [comment]
@jjasghar No problem! Just your interest and helpful approach got me far. :)

**Comment by jjasghar** [comment]
Going to close this because #150 and #151 are the first steps to getting this done. /cc @cphrmky
