### ISSUE TITLE
[softlayer] create and delete networks with chef-provisioning-fog

### ISSUE THREAD

**Issue by jjasghar** [chef/chef-provisioning-fog#150]
@cphrmky 
After reading through [networking](https://github.com/fog/fog-softlayer/blob/master/examples/network.md) for fog-softlayer, the ability to create and destroy networks would help out the user's provisioning scripts.

**Comment by jjasghar** [comment]
@cphrmky any progress here?

**Comment by cphrmky** [comment]
Hi @jjasghar ,

> the ability to create and destroy networks would help out

This exists, I think clarity is needed depending on how you're defining "networks".  You mean acutal VLANs in the SDN sense?  Or subnets in the "hey-I-need-an-IP-address" sense?  Also, there are "global IP addresses" which are a special and fun SLayer hack that allow you to move a single IP address (v4 or v6 take your pick) in isolation around to any SLayer datacenter at any time.

fog-softlayer already supports the ability to create and destroy VLANs, and also subnets (also global IP addresses).  There's some hierarchy here, which directly maps to the way that the SLayer API structures things.

A `SoftLayer::Account` has `0 - N` `VLAN`s.
A `VLAN` is `public` `XOR` `private`
A `VLAN` has `1 - N` `subnets`. [subnets may be either IPv4 or IPv6]
If the `VLAN` is `public` any `subnet` attached to it will contain publicly routable IP addresses.
If the `VLAN` is `private` any `subnet` attached to it will contain private network IP addresses. (Accessible only from other points on the SLayer private network or via a VPN connection).

An example of creating a VLAN looks like this.

```ruby
require 'fog/softlayer'
sl = Fog::Network[:softlayer]

# instantiate a Fog::Network::Softlayer::Datacenter object
wdc01 = sl.datacenters.by_name('wdc01')
# we can list out the routers thusly
wdc01.routers
# => [{"hostname"=>"bcr01.wdc01", "id"=>16358},
    # {"hostname"=>"bcr02.wdc01", "id"=>40379},
    # ...
    # {"hostname"=>"fcr01.wdc01", "id"=>16357},
    # {"hostname"=>"fcr02.wdc01", "id"=>40378},
    # ...
    # ]

# the SLayer convention is to name private or "backend" routers beginning with bcr and public or "frontend" routers with fcr
# so you need to choose a frontend router for a public VLAN, likewise, if you're creating a private VLAN, you need to choose a router which has a name beginning with bcr
opts = {
     :name => 'my-new-network', 
     :datacenter => wdc01,
     :router => wdc01.routers[0],
     :network_space => 'PRIVATE',
    }

sl.networks.create(opts)
```

The above is excerpted from the [networking examples](https://github.com/fog/fog-softlayer/blob/master/examples/network.md) on the fog-softlayer repo.  I'm noticing as I write this that we don't seem to have explicit examples for creating additional subnets to be attached to an existing VLAN, which we should as it's functionality that fog-sofltayer already supports.  

Let me know if the subnet stuff is closer to the thrust of the ask here and I'll try to find time to put that togther and add it to the example docs that are already there.

**Comment by jjasghar** [comment]
Ah, ok. As long as there is basic support until someone explicitly asks for it, I think we're fine. Though we do have a `examples/` directory, can you add a simple example and update the README with the support?

**Comment by jjasghar** [comment]
Waiting for https://github.com/chef/chef-provisioning-fog/pull/149 to be merged, which'll add the examples per @ causton81
