### ISSUE TITLE
[softlayer] create and delete storage with chef-provisioning-fog

### ISSUE THREAD

**Issue by jjasghar** [chef/chef-provisioning-fog#151]
@cphrmky 
After reading through [storage](https://github.com/fog/fog-softlayer/blob/master/examples/storage.md) for fog-softlayer, the ability to create and destroy storage containers would help out the user's provisioning scripts.

The ability to upload a file from another location to the created container would be a nice to have.

**Comment by jjasghar** [comment]
@cphrmky any progress here?

**Comment by cphrmky** [comment]
@jjasghar ,

The ability to create and destroy storage containers exists with fog-softlayer already.

Second item from [storage](https://github.com/fog/fog-softlayer/blob/master/examples/storage.md#use-the-models) shows how to create a directory or container.

Are you looking for me to implement something that ties this together in chef-provisioning-fog itself?

**Comment by jjasghar** [comment]
I think I'm just looking for documentation on what we have and if there was any interest in adding more features. You can see what I'm specifically asking for in #150.
