### ISSUE TITLE
Logging to files instead of stdout

### ISSUE THREAD

**Issue by ckaushik** [chef/chef-provisioning-fog#153]
I am using machine_batch to spin up hundreds of instances in parallel. The chef provisioning log is too cluttered because of this and I would like to have logs from different instances go to separate log files.

chef provisioning has config[:stream_stdout] and config[:stream_stderr] as options we can pass in when creating Transport SSH object. But we need fog driver to open files, pass it to transport object and close them after the converge, for the logs to be written to disk

**Comment by jjasghar** [comment]
No movement, if you'd like to help I'd love to see PR, but I'm closing this due to no movement.
