### ISSUE TITLE
ea3ae05cb8150701ca26ae66052e57530415eff1 changes server.state to server.status for all fog drivers

### ISSUE THREAD

**Issue by causton81** [chef/chef-provisioning-fog#161]
fog-softlayer at least does not define a `status` method. Do the other fog drivers work okay with latest master?

**Comment by jek-a** [comment]
No, I have the same problem with EC2 driver after merging [#155](https://github.com/chef/chef-provisioning-fog/pull/155) pull request into the master.

**Comment by jjasghar** [comment]
Oh, interesting. I'll put some time this week to resolve this. Thanks for the reports.

**Comment by jjasghar** [comment]
I'm betting @hh already removed this? https://github.com/chef/chef-provisioning-fog/pull/160 any chance y'all can give this a shot?

**Comment by jjasghar** [comment]
Resolved not removed. Stupid autocorrect.

**Comment by causton81** [comment]
Seems about right. I'll give it a shot.

**Comment by jek-a** [comment]
I think that @hh fixed the [server.rb](https://github.com/fog/fog/blob/master/lib/fog/openstack/models/compute/server.rb) for the openstack driver, but the fog [driver.rb](https://github.com/chef/chef-provisioning-fog/blob/master/lib/chef/provisioning/fog_driver/driver.rb) still have `status` method

**Comment by jek-a** [comment]
The EC2 driver works after the [#160](https://github.com/chef/chef-provisioning-fog/pull/160).

**Comment by causton81** [comment]
Yes, seems okay after #160.

**Comment by jjasghar** [comment]
Awesome! I'll get it released for tomorrow. Any chance I can get y'all to write examples like what we have for Rackspace/OpenStack/Digital Ocean?

It would be great to have them for EC2 and Softlayer.

**Comment by causton81** [comment]
I will plan to add examples with #149, but waiting on fog-softlayer PR to go thru first.

**Comment by jjasghar** [comment]
Awesome @caustin81. We have a "standard" way for examples now, so copypasta and change specifics everything should be perfect.

**Comment by jjasghar** [comment]
@jek-a can i convince you to do the EC2 example documentation? You can cargo cult this https://github.com/chef/chef-provisioning-fog/commit/5c04061788fc2ff204bba8faf04fcd7dc2a34015 commit as an example.

/cc @causton81 for a template

**Comment by jek-a** [comment]
Sure, I can do it.

**Comment by jjasghar** [comment]
Waiting for https://github.com/fog/fog/pull/3849

**Comment by jjasghar** [comment]
Check #160 for a temp work around if https://github.com/fog/fog/pull/3849 isn't merged "quickly."

**Comment by jjasghar** [comment]
https://github.com/chef/chef-provisioning-fog/pull/164 when the new fog gem is released.

**Comment by jjasghar** [comment]
When Fog does another release I'll cut a new gem. Master should be working now though. Please :+1: this if you can.

**Comment by jjasghar** [comment]
any luck on verifying this? /cc @jek-a @causton81

**Comment by causton81** [comment]
Sorry, was busy today. Will try tomorrow AM.

**Comment by causton81** [comment]
:+1:

**Comment by jjasghar** [comment]
Awesome, I'll open an issue to track the docs for @jek-a and close this.
