### ISSUE TITLE
EC2 documentation

### ISSUE THREAD

**Issue by jjasghar** [chef/chef-provisioning-fog#168]
@jek-a is going to take care of some EC2 documentation for chef-provisioning-fog. Thanks!

**Comment by jek-a** [comment]
I will do it on this week. I'm little busy now. I don't use AWS as a cloud provider, I use our corporate cloud as a cloud provider, becuase it supports EC2 API. Although, I don't use `knife.rb`. I use AWS approach `~/.aws/config` and `~/.aws/credentials` to store: `aws_access_key_id`, `aws_secret_access_key`. With that approach you can work with multiple accounts. I tried to use `knife.rb`, but I could not pass custom `ec2_endpoint` and `iam_endpoint` variables for our cloud. I hope that this will work.

**Comment by jjasghar** [comment]
@jek-a awesome thanks. Any documentation that i can verify then merge is what i'm looking for. 

If it's only done via `.aws/config` and `.aws/credentials` so be it. Anything right now is better then nothing.

And we do have a "standard" way of the documentation now, something like: https://github.com/chef/chef-provisioning-fog/pull/163

**Comment by jjasghar** [comment]
@jek-a can you add https://github.com/chef/chef-provisioning-fog/pull/120 as part of your documentation? Thanks!

**Comment by jjasghar** [comment]
@jek-a any progress here?

**Comment by jjasghar** [comment]
@jek-a ping :smile_cat:

**Comment by jjasghar** [comment]
https://github.com/chef/chef-provisioning-fog/pull/175 Resolves what I was looking for.
