### ISSUE TITLE
Rackspace RackConnect v3 support

### ISSUE THREAD

**Issue by SympaHannuPiki** [chef/chef-provisioning-fog#178]
Hi there,

it would be awesome if Rackspace driver supports RackConnect v3 on some day. Currently driver is creating server as it should, but it can't find suitable IP address at the moment when server goes up nor afterwards when trying to re-run provision scripts.

```
RuntimeError: machine[SB-REPORTING-99] (sympa_provisioning::sandbox_reporting line 33) had an error: RuntimeError: Server fae38d53-bc32-46cf-8eec-4cbf36d6a559 has no private or public IP address!
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-fog-0.18.0/lib/chef/provisioning/fog_driver/driver.rb:701:in `create_ssh_transport'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-fog-0.18.0/lib/chef/provisioning/fog_driver/driver.rb:276:in `transport_for'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-fog-0.18.0/lib/chef/provisioning/fog_driver/driver.rb:433:in `wait_for_transport'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-fog-0.18.0/lib/chef/provisioning/fog_driver/driver.rb:215:in `ready_machine'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.7.0/lib/chef/provider/machine.rb:39:in `block in <class:Machine>'
(eval):2:in `block in action_ready'
```

I already found issue #124 where one workaround was mentioned, but that didn't work out for me at least.

> As a workaround we make use of the transport_address_location => :private_ip (+ deprecated use_private_ip_for_ssh => true) to get round the RackConnect public IP change. I mentioned that initially I thought that was not doing the trick, however it does seem to be doing the trick."

Let see how things goes on after this passed and Windows server login is tried with WinRM. If we could define address for WinRM with custom script/method to be run, that would be enough too as finding IP from the API isn't that big thing when compared to what can be achieved with Chef Provisioning.

Any great ideas how to bypass this issue with current version?

Kind regards,
Hannu Piki

**Comment by jjasghar** [comment]
Pinging @martinb3 , do you know anyone who can make this happen for @SympaHannuPiki ? I have little to no exposure to RackConnect :(

**Comment by martinb3** [comment]
@SympaHannuPiki While this isn't directly related, are you running your provisioning node also on the same RCv3 network? Or from another external source?

I'm assuming the main issue is going to be that we'd need to teach the fog driver to (a) wait for RC automation and (b) use the RCv3 APIs to lookup the appropriate IP address to access the new server.

**Comment by SympaHannuPiki** [comment]
@martinb3, sorry for late answer. Answer is yes, if dedicated server and it's network is counted as RCv3 network as it is connected to the target cloud.

**Comment by jjasghar** [comment]
No movement, if you'd like to help I'd love to see PR, but I'm closing this due to no support.
