### ISSUE TITLE
xenserver provider not working against xenserver 6.5

### ISSUE THREAD

**Issue by chrodriguez** [chef/chef-provisioning-fog#183]
I've been playing around with chef-provisioning-fog using xenserver provider and it seems to be broken. In fact, the current implementation is outdated as mentioned [in fog-xenserver issue 53](https://github.com/fog/fog-xenserver/issues/48)

There is an other issue #123, I believe it is related with this issue...

I'll try to modify this provider to be compatible with newer versions of xen api

**Comment by tromenskaya** [comment]
This is an automatically generated message.

tatyana@yahoo-inc.com is no longer with Yahoo! Inc.

Your message will not be forwarded.

If you have a sales inquiry, please email yahoosales@yahoo-inc.com and someone will follow up with you shortly.

If you require assistance with a legal matter, please send a message to legal-notices@yahoo-inc.com

Thank you!
