### ISSUE TITLE
DigitalOcean fog driver does not work

### ISSUE THREAD

**Issue by 01sas** [chef/chef-provisioning-fog#191]
DigitalOcean fog driver does not work. See details [here](http://stackoverflow.com/questions/37880345/spawning-digital-ocean-machines-using-chef-provisioning/38635911#38635911) and [here](https://github.com/fog/fog/issues/3869). But the core problem is already fixed in [fog-digitalocean](https://github.com/fog/fog-digitalocean/). Actually they extract DigitalOcean into a separate project. So I think that you should use this as dependency.

**Comment by tromenskaya** [comment]
This is an automatically generated message.

tatyana@yahoo-inc.com is no longer with Yahoo! Inc.

Your message will not be forwarded.

If you have a sales inquiry, please email yahoosales@yahoo-inc.com and someone will follow up with you shortly.

If you require assistance with a legal matter, please send a message to legal-notices@yahoo-inc.com

Thank you!

**Comment by jjasghar** [comment]
Yep, we've had some issues back and forth with DO and this gem. I'm going to spend some time walking through all these issues again.

**Comment by jjasghar** [comment]
I was able to get the gem to work:
```

    - creating machine mysimpleserver on fog:DigitalOcean:
    -   image_distribution: "Ubuntu"
    -   image: "18572320"
    -   flavor_name: "2GB"
    -   region_name: "London 1"
    -   key_name: "mbp"
    -   tags: {"Name"=>"mysimpleserver", "BootstrapId"=>"chefzero://localhost:8889/nodes/mysimpleserver", "BootstrapHost"=>"JJs-MacBook-Pro.local", "BootstrapUser"=>"jjasghar"}
    -   size: "2gb"
    -   region: "lon1"
    -   ssh_keys: [xxxxxx]
    -   name: "mysimpleserver"
    -   version: :v2
    - machine mysimpleserver created as 21222540 on fog:DigitalOcean:[2016-08-01T12:44:45-05:00] INFO: Processing chef_node[mysimpleserver] action create (basic_chef_client::block line 57)
   - create node mysimpleserver at chefzero://localhost:8889
    -   add normal.tags = ["tagtagtag"]
    -   add normal.chef_provisioning = {"reference"=>{"driver_url"=>"fog:DigitalOcean:", "driver_version"=>"0.19.0", "creator"=>"", "allocated_at"=>1470073482, "key_name"=>"mbp", "server_id"=>21222540}}
    -   update run_list from [] to ["recipe[somerecipe]"]
    - waiting for mysimpleserver (21222540 on fog:DigitalOcean:) to be ready, API attempt 1/12 ...
    - mysimpleserver is now ready
```

https://github.com/chef/chef-provisioning-fog/pull/192

I think this breaks something else though. I'm looking for the issue now.

**Comment by jjasghar** [comment]
Ah yes.

https://github.com/chef/chef-provisioning-fog/issues/170

So 1.37.0 of the gem changes the `status` method for everything. It broke everything and I mean everything if you look at https://github.com/chef/chef-provisioning-fog/issues/170. To you point it was fixed but not really.

My best suggestions is to do what i did in #192 and do a bundle exec to use DO.

the `fog-digitalocean` gem isn't on rubygems because it was never completed. I'm moving to work on that now.

**Comment by jjasghar** [comment]
@01sas i believe this should fix your issue now: https://github.com/chef/chef-provisioning-fog/pull/193 I should be pushing this today.
