### ISSUE TITLE
Problem with converging instances when keypair is missing

### ISSUE THREAD

**Issue by baurzhan-konurbayev** [chef/chef-provisioning-fog#196]
Hello,

I am using chef-provisioning-fog to converge Openstack instances.
I am getting error message:

> Server has key name 'test_keypair', but the corresponding private key was not found locally.

I don't have keypair named 'test_keypair, but I have root ssh access to the instances.

Could you, please, suggest how to deal with this situation?
Can chef-provisioner accept the key that I provided in :ssh_options => :keys?
Please, see the short snippet of my provisioning configuration:

>  :machine_options=>
>   {:ssh_username=>"root",
>    :bootstrap_options=>
>     {:image_ref=>"a2d87320-e399-4db7-864e-086d3d7dcd09",
>      :flavor_ref=>"ce104e9d-80fe-424a-bfab-a7b072fd87d1",
>      :key_name=>"my_fogkey",
>      :nics=>[{:net_id=>"266f074c-dc9c-405c-9dd7-3d00f01b0fbc"}],
>      :floating_ip_pool=>"ExternalNetwork",
>      :name=>"my_instance"},
>    :ssh_options=>{:keys=>["~/.ssh/id_rsa"]}}

My private key "id_rsa" has ssh access for root user to an instance.
Why does chef provisioner compare it to key-pair and want to use it?

I need to converge instances of another user. This is legal in our enterprise. 

Could you, guys, please, suggest what I am doing wrong or maybe I have some configuration issues?

Appreciate any help. Thanks.

**Comment by baurzhan-konurbayev** [comment]
So far, I am thinking to add private keys contents to :key_data both for key pair's private key and the one from :keys.
This way both of them will work, any other ideas?

**Comment by jjasghar** [comment]
Have you tried the [simple](https://github.com/chef/chef-provisioning-fog/blob/master/examples/openstack/simple.rb) example? Has it ever worked for you?

**Comment by baurzhan-konurbayev** [comment]
Thanks for answering. We do provision instances for both Openstack and AWS. 
So, no need to try the simple.
We our patched gems for chef-provisioning-fog and chef-provisioning-aws.
For, chef-provisioning-fog we force usage of ssh agent before that error message. This way we can use a key for root access different from the key-pair's private key.

**Comment by jjasghar** [comment]
Ah ok. I'm not 100% sure what to advise here. I'd go though removing bits and pieces of your complexity and debugging down to what's broken. There are too many environmental variables here for me to give good advice. If you have and suggestions or more thoughts please reopen this issue.
