### ISSUE TITLE
Openstack Identity v3 support?

### ISSUE THREAD

**Issue by rneu31** [chef/chef-provisioning-fog#198]
The documentation does not specify if v3 is supported and I haven't been able to find any examples elsewhere. Thanks.

**Comment by jjasghar** [comment]
I know I've never tested against the v3 systems. I don't have access nor an environment that supports v3.

Assuming you use the https://github.com/fog/fog-openstack with v3, there is no reason why we couldn't extend it to.

I'm more then willing to look at PRs for this, but its unlikely it'll be written by anyone at Chef in the near future.

Please reopen this if you have any other questions or thoughts.
