### ISSUE TITLE
Unable to authenticate with OpenStack Newton project

### ISSUE THREAD

**Issue by phanikumar1210** [chef/chef-provisioning-fog#201]
I have provided my auth_url, username and key for Newton OpenStack and I am getting 400 bad request. I have provided the following as my auth url **http://192.168.8.25:5000/v3/tokens** somehow it is saying unexpected token auth in the url in OpenStack log file.  Could anyone help me out on this.

**Comment by jjasghar** [comment]
As you can see from the documentation:

```ruby
 :openstack_auth_url => 'http://YOUROPENSTACK-CLOUD:5000/v2.0/tokens',
````

Right now this is only tested against v2 of the API. There is a strong possiblity something has changed. If you are willing to debug and make the changes I'd love to see the PR.

**Comment by jjasghar** [comment]
No movement, if you'd like to help I'd love to see PR, but I'm closing this due to no support.
