### ISSUE TITLE
Getting Error undefined method `location` for #Array:xxxx>

### ISSUE THREAD

**Issue by abhishekdoshi** [chef/chef-provisioning-fog#210]
I got error while execute Fog Provisioning for AWS. if i use aws driver, it's successfully execute , but unable to provisioning using fog:AWS driver

**Comment by jjasghar** [comment]
We only have AWS in this plugin for legacy reasons, if you want AWS support you should look at the https://github.com/chef/chef-provisioning-aws instead. 🤘
