### ISSUE TITLE
AWS: ArgumentError: wrong number of arguments (given 0, expected 1..2)

### ISSUE THREAD

**Issue by BGmot** [chef/chef-provisioning-fog#211]
Chef Development Kit Version: 1.3.43.
Incompatibility with the latest chef-provisioning/cheffish? Any action with machine resource results in following:
```
Generated at 2017-06-01 12:17:23 -0400
ArgumentError: machine[<snip>] (<snip>::default line 49) had an error: ArgumentError: wrong number of arguments (given 0, expected 1..2)
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/mixlib-config-2.2.4/lib/mixlib/config.rb:255:in `default'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/ohai-8.23.0/lib/ohai/mash.rb:179:in `from_hash'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/cheffish-5.0.1/lib/cheffish/merged_config.rb:7:in `block in initialize'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/cheffish-5.0.1/lib/cheffish/merged_config.rb:7:in `map'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/cheffish-5.0.1/lib/cheffish/merged_config.rb:7:in `initialize'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-fog-0.24.0/lib/chef/provisioning/fog_driver/providers/aws.rb:344:in `new'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-fog-0.24.0/lib/chef/provisioning/fog_driver/providers/aws.rb:344:in `compute_options_for'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-provisioning-fog-0.24.0/lib/chef/provisioning/fog_driver/driver.rb:142:in `canonicalize_url'
/home/eyurchen/.chefdk/gem/ruby/2.3.0/gems/chef-provisioning-2.3.2/lib/chef/provisioning.rb:74:in `driver_for_url'
/home/eyurchen/.chefdk/gem/ruby/2.3.0/gems/chef-provisioning-2.3.2/lib/chef/provisioning/chef_run_data.rb:105:in `driver_for_url'
/home/eyurchen/.chefdk/gem/ruby/2.3.0/gems/chef-provisioning-2.3.2/lib/chef/provisioning/chef_run_data.rb:84:in `driver_for'
/home/eyurchen/.chefdk/gem/ruby/2.3.0/gems/chef-provisioning-2.3.2/lib/chef/provider/machine.rb:108:in `new_driver'
/home/eyurchen/.chefdk/gem/ruby/2.3.0/gems/chef-provisioning-2.3.2/lib/chef/provider/machine.rb:25:in `block in <class:Machine>'
(eval):2:in `block in action_allocate'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/provider.rb:361:in `instance_eval'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/provider.rb:361:in `compile_and_converge_action'
(eval):2:in `action_allocate'
/home/eyurchen/.chefdk/gem/ruby/2.3.0/gems/chef-provisioning-2.3.2/lib/chef/provider/machine.rb:38:in `block in <class:Machine>'
(eval):2:in `block in action_ready'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/provider.rb:361:in `instance_eval'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/provider.rb:361:in `compile_and_converge_action'
(eval):2:in `action_ready'
/home/eyurchen/.chefdk/gem/ruby/2.3.0/gems/chef-provisioning-2.3.2/lib/chef/provider/machine.rb:56:in `block in <class:Machine>'
(eval):2:in `block in action_converge'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/provider.rb:361:in `instance_eval'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/provider.rb:361:in `compile_and_converge_action'
(eval):2:in `action_converge'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/provider.rb:145:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource.rb:622:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:69:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:97:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:97:in `block in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/runner.rb:96:in `converge'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:670:in `block in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:665:in `catch'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:665:in `converge'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:704:in `converge_and_save'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:284:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:295:in `block in fork_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:283:in `fork'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:283:in `fork_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:248:in `block in run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:236:in `run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:450:in `loop'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:434:in `run_application'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:59:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/bin/chef-client:26:in `<top (required)>'
/opt/chefdk/bin/chef-client:58:in `load'
/opt/chefdk/bin/chef-client:58:in `<main>'


```

**Comment by grahamja** [comment]
I am getting this with Fog:OpenStack also and ChefDK 2.0.26 (I also tried going back to the last 1.X ChefDK with the same results)

Chef Development Kit Version: 2.0.26
chef-client version: 13.2.20
delivery version: master (17c1b0fed9be4c70f69091a6d21a4cbf0df60a23)
berks version: 6.2.0
kitchen version: 1.16.0
inspec version: 1.30.0


Generated at 2017-07-13 13:33:48 -0700
ArgumentError: machine[test] (@recipe_files::/Users/jsong/gap_git/iaas/chef_servers/backend_servers.rb line 28) had an error: ArgumentError: wrong number of arguments (given 0, expected 1..2)
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/mixlib-config-2.2.4/lib/mixlib/config.rb:255:in `default'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.2.0/lib/ohai/mash.rb:179:in `from_hash'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/cheffish-13.0.0/lib/cheffish/merged_config.rb:6:in `block in initialize'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/cheffish-13.0.0/lib/cheffish/merged_config.rb:6:in `map'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/cheffish-13.0.0/lib/cheffish/merged_config.rb:6:in `initialize'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-provisioning-fog-0.21.0/lib/chef/provisioning/fog_driver/providers/openstack.rb:48:in `new'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-provisioning-fog-0.21.0/lib/chef/provisioning/fog_driver/providers/openstack.rb:48:in `compute_options_for'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-provisioning-fog-0.21.0/lib/chef/provisioning/fog_driver/driver.rb:142:in `canonicalize_url'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-provisioning-2.4.0/lib/chef/provisioning.rb:74:in `driver_for_url'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-provisioning-2.4.0/lib/chef/provisioning/chef_run_data.rb:105:in `driver_for_url'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-provisioning-2.4.0/lib/chef/provisioning/chef_run_data.rb:84:in `driver_for'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-provisioning-2.4.0/lib/chef/provider/machine.rb:108:in `new_driver'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-provisioning-2.4.0/lib/chef/provider/machine.rb:25:in `block in <class:Machine>'
(eval):2:in `block in action_allocate'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/provider.rb:211:in `instance_eval'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/provider.rb:211:in `compile_and_converge_action'
(eval):2:in `action_allocate'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-provisioning-2.4.0/lib/chef/provider/machine.rb:38:in `block in <class:Machine>'
(eval):2:in `block in action_ready'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/provider.rb:211:in `instance_eval'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/provider.rb:211:in `compile_and_converge_action'
(eval):2:in `action_ready'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-provisioning-2.4.0/lib/chef/provider/machine.rb:56:in `block in <class:Machine>'
(eval):2:in `block in action_converge'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/provider.rb:211:in `instance_eval'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/provider.rb:211:in `compile_and_converge_action'
(eval):2:in `action_converge'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/provider.rb:171:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/resource.rb:591:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/runner.rb:70:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/runner.rb:98:in `block (2 levels) in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/runner.rb:98:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/runner.rb:98:in `block in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/runner.rb:97:in `converge'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/client.rb:715:in `block in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/client.rb:710:in `catch'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/client.rb:710:in `converge'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/client.rb:749:in `converge_and_save'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/client.rb:286:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:291:in `block in fork_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:279:in `fork'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:279:in `fork_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:244:in `block in run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:232:in `run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application/client.rb:469:in `sleep_then_run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application/client.rb:458:in `block in interval_run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application/client.rb:457:in `loop'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application/client.rb:457:in `interval_run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application/client.rb:441:in `run_application'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:59:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/bin/chef-client:26:in `<top (required)>'
/opt/chefdk/bin/chef-client:264:in `load'
/opt/chefdk/bin/chef-client:264:in `<main>'

>>>> Caused by ArgumentError: wrong number of arguments (given 0, expected 1..2)
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/mixlib-config-2.2.4/lib/mixlib/config.rb:255:in `default'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.2.0/lib/ohai/mash.rb:179:in `from_hash'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/cheffish-13.0.0/lib/cheffish/merged_config.rb:6:in `block in initialize'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/cheffish-13.0.0/lib/cheffish/merged_config.rb:6:in `map'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/cheffish-13.0.0/lib/cheffish/merged_config.rb:6:in `initialize'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-provisioning-fog-0.21.0/lib/chef/provisioning/fog_driver/providers/openstack.rb:48:in `new'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-provisioning-fog-0.21.0/lib/chef/provisioning/fog_driver/providers/openstack.rb:48:in `compute_options_for'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-provisioning-fog-0.21.0/lib/chef/provisioning/fog_driver/driver.rb:142:in `canonicalize_url'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-provisioning-2.4.0/lib/chef/provisioning.rb:74:in `driver_for_url'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-provisioning-2.4.0/lib/chef/provisioning/chef_run_data.rb:105:in `driver_for_url'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-provisioning-2.4.0/lib/chef/provisioning/chef_run_data.rb:84:in `driver_for'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-provisioning-2.4.0/lib/chef/provider/machine.rb:108:in `new_driver'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-provisioning-2.4.0/lib/chef/provider/machine.rb:25:in `block in <class:Machine>'
(eval):2:in `block in action_allocate'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/provider.rb:211:in `instance_eval'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/provider.rb:211:in `compile_and_converge_action'
(eval):2:in `action_allocate'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-provisioning-2.4.0/lib/chef/provider/machine.rb:38:in `block in <class:Machine>'
(eval):2:in `block in action_ready'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/provider.rb:211:in `instance_eval'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/provider.rb:211:in `compile_and_converge_action'
(eval):2:in `action_ready'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-provisioning-2.4.0/lib/chef/provider/machine.rb:56:in `block in <class:Machine>'
(eval):2:in `block in action_converge'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/provider.rb:211:in `instance_eval'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/provider.rb:211:in `compile_and_converge_action'
(eval):2:in `action_converge'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/provider.rb:171:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/resource.rb:591:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/runner.rb:70:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/runner.rb:98:in `block (2 levels) in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/runner.rb:98:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/runner.rb:98:in `block in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/runner.rb:97:in `converge'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/client.rb:715:in `block in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/client.rb:710:in `catch'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/client.rb:710:in `converge'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/client.rb:749:in `converge_and_save'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/client.rb:286:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:291:in `block in fork_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:279:in `fork'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:279:in `fork_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:244:in `block in run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:232:in `run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application/client.rb:469:in `sleep_then_run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application/client.rb:458:in `block in interval_run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application/client.rb:457:in `loop'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application/client.rb:457:in `interval_run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application/client.rb:441:in `run_application'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/lib/chef/application.rb:59:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/bin/chef-client:26:in `<top (required)>'
/opt/chefdk/bin/chef-client:264:in `load'
/opt/chefdk/bin/chef-client:264:in `<main>'

**Comment by thommay** [comment]
Please could one of you provide a sample recipe and how it's being run, to make a replication case easier.

**Comment by chilicheech** [comment]
I get the same error on any ChefDK > 1.1.16. That's the latest one that works for me.

**Comment by bbuczynski** [comment]
I gave up after trying installing different versions of chefdk, chef-provisioning-fog etc.  However I fixed the problem by creating a gem that would patch the following files:
..../ruby/gems/2.3.0/gems/cheffish-5.0.1/lib/cheffish/merged_config.rb
..../ruby/2.3.0/gems/chef-provisioning-fog-0.24.0/lib/chef/provisioning/fog_driver/driver.rb
You could patch it directly inside those files but then it becomes a bigger pain to maintain it. So instead I created a new gem 'openstack_patch' and just call require in my recipes to fix the issue.  
The patch fixes the following:
```ruby
require 'chef/provisioning'
require 'cheffish'
require 'chef/provisioning/fog_driver/driver'
require 'chef/provisioning/fog_driver/providers/openstack'

module Cheffish
  class MergedConfig
    def initialize(*configs)
###### PATCH
      @configs = configs
      @merge_arrays = {}
###### BEFORE
      # @configs = configs.map { |config| Chef::Mash.from_hash config }
      # @merge_arrays = Chef::Mash.new
###### END
    end
  end
end

class Chef
  module Provisioning
    module FogDriver
      class Driver < Provisioning::Driver
        def servers_for(specs_and_options)
          result = {}
####### PATCH
          specs_and_options.each do |machine_spec, machine_options|
####### BEFORE
          # machine_specs.each do |machine_spec, machine_options|
####### END 
            if machine_spec.reference
              if machine_spec.reference['driver_url'] != driver_url
                raise "Switching a machine's driver from #{machine_spec.reference['driver_url']} to #{driver_url} for is not currently supported!  Use machine :destroy and then re-create the machine on the new driver."
              end
              result[machine_spec] = compute.servers.get(machine_spec.reference['server_id'])
            else
              result[machine_spec] = nil
            end
          end
          result
        end
      end
    end
  end
end
```

**Comment by tas50** [comment]
I'm going to close this out at this point since we removed support for fog-aws and instead suggest that users use fog-provisioning-aws which uses the native aws-sdk and resolves a large number of longstanding AWS issues.
