### ISSUE TITLE
fails to authenticate (chef server 10.18.2)

### ISSUE THREAD

**Issue by reesew** [chef/chef-provisioning-fog#26]
AWS instances don't finish the bootstrap process, they fail with a 401 status when attempting to authenticate to the chef server with /etc/chef/client.pem. I've double checked and even regenerated the validation.pem on the chef server. After a machine fails to run chef-client, I copy the same private key as specified by `validation_key` in knife.rb to the machine, delete client.pem, and rerun chef-client, and then it works. I'm also able to bootstrap using knife's ec2 plugin using the same private key. The key specified by `client_key` in knife.rb and `:signing_key_filename` in `with_chef_server` seems to work as well, as it fails earlier when this is modified. 
I haven't been able to determine whether this is a problem with the driver, or my configuration or chef server. Note: I do have an environment where chef-metal works properly and manages multiple AWS machines. The problematic chef-server is version 10.18.2 while the working one is 11.something. Is there a minimum server version requirement? Do I need to upgrade?

**Comment by jjasghar** [comment]
Please reopen this if it's still relevant, we're on chef server 12+ now.
