### ISSUE TITLE
Support loading AWS credentials from ~/.aws/credentials

### ISSUE THREAD

**Issue by schisamo** [chef/chef-provisioning-fog#41]
Amazon's tooling now looks for default credentials at `~/.aws/credentials`:

http://docs.aws.amazon.com/AWSSdkDocsRuby/latest/DeveloperGuide/prog-basics-creds.html
http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html
http://docs.aws.amazon.com/aws-sdk-php/guide/latest/quick-start.html
http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html

We should probably deprecate the use of `~/.aws/config` and begin using `~/.aws/credentials` for consistency.

**Comment by jkeiser** [comment]
We now support it, yay!
