### ISSUE TITLE
When driver is specified but not region, driver_url does not contain region

### ISSUE THREAD

**Issue by nathenharvey** [chef/chef-provisioning-fog#52]
When driver is specified but the region is missing, the driver_url gets set without a region.

    "metal": {
        "location": {
          "driver_url": "fog:AWS:862552916454:",
          "driver_version": "0.9",
          "server_id": "i-b653b958",
          "creator": "user/nathenharvey",
          "allocated_at": 1410281374,
          "key_name": "chef-nathenharvey"
        }
      }
    ...

**Comment by jjasghar** [comment]
I don't think this is relevant anymore. If it is please reopen.
