### ISSUE TITLE
driver_url without a region fails with terrible error message

### ISSUE THREAD

**Issue by nathenharvey** [chef/chef-provisioning-fog#53]
When driver_url does not contain region, e.g. `"driver_url": "fog:AWS:862552916454:"`, the machine resource will fail with the following error:

```
No AWS profile specified!  Are you missing something in the Chef config or ~/.aws/config?
```

A better error message should be displayed for easier troubleshooting.

**Comment by tas50** [comment]
I'm going to close this out at this point since we removed support for fog-aws and instead suggest that users use fog-provisioning-aws which uses the native aws-sdk and resolves a large number of longstanding AWS issues.
