### ISSUE TITLE
tugboatrc seems to override with_machine_options in bad ways

### ISSUE THREAD

**Issue by jdblack** [chef/chef-provisioning-fog#56]
Despite not setting an image default in .tugboatrc, and setting an image_name within machine_options, it seems that imageid is defaulting to 0.  

~/.tugboatrc  
```
---
authentication:
  client_key: XXXX
  api_key: YYYY
ssh:
  ssh_user: jblack
  ssh_key_path: /home/jblack/.ssh/id_rsa
  ssh_port: '22'
defaults:
  region: 4
```

linuxguru::simple_stack
```
require 'chef_metal_fog'

with_driver 'fog:DigitalOcean', :compute_options => {
   ¦ :digitalocean_api_key => Chef::Config[:digital_ocean_api_key],
   ¦  ¦:digitalocean_client_id => Chef::Config[:digital_ocean_client_id]
}

with_chef_server 'https://chef.linuxguru.net',
   :client_name => Chef::Config[:node_name],
   :signing_key_filename => Chef::Config[:client_key]



with_machine_options(
   :bootstrap_options => {
   ¦  image_name: 'Ubuntu 14.04 x64',
   ¦  region_name: 'New York 2',
   ¦  key_name: 'jblack'
   }
)

machine 'testbox' do
   tag 'itsname'
```

root@comet
~$ chef-client -r 'linuxguru::stack_simple'
[2014-09-16T22:50:40-07:00] WARN: 
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
SSL validation of HTTPS requests is disabled. HTTPS connections are still
encrypted, but chef is not able to detect forged replies or man in the middle
attacks.

To fix this issue add an entry like this to your configuration file:

```
  # Verify all HTTPS connections (recommended)
  ssl_verify_mode :verify_peer

  # OR, Verify only connections to chef-server
  verify_api_cert true
```

To check your SSL configuration, or troubleshoot errors, you can use the
`knife ssl check` command like so:

```
  knife ssl check -c /etc/chef/client.rb
```

* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

Starting Chef Client, version 11.16.2
resolving cookbooks for run list: ["linuxguru::stack_simple"]
Synchronizing Cookbooks:
  - linuxguru
  - apache2
  - iptables
  - logrotate
  - pacman
  - apt
  - asterisk
  - build-essential
  - unimrcp
  - yum
  - bind
  - bind9
  - chef-client
  - cron
  - chef-server
  - docker
  - aufs
  - modules
  - device-mapper
  - git
  - dmg
  - windows
  - chef_handler
  - runit
  - yum-epel
  - golang
  - homebrew
  - lxc
  - dpkg_autostart
  - sysctl
  - ohai
  - elasticsearch
  - ark
  - 7-zip
  - gitolite
  - perl
  - hostname
  - hostsfile
  - iptables-ng
  - java
  - jenkins
  - kibana
  - mysql
  - yum-mysql-community
  - nfs
  - line
  - openvpn
  - rsyslog
  - selinux
  - ssh-keys
  - sudo
  - swap
  - td-agent
  - users
Compiling Cookbooks...
Converging 1 resources
Recipe: linuxguru::stack_simple
  * machine[testbox] action converge[2014-09-16T22:51:24-07:00] WARN: Mismatched key size!  /home/jblack/.ssh/id_rsa is 4096 bytes, desired is 2048 bytes.  Use action :regenerate to force key regeneration.

    - creating machine testbox on fog:DigitalOcean:df6b7ab16f7acfd50d15fa2a46d1cc5d
    -   image_name: "Ubuntu 14.04 x64"
    -   region_name: "New York 2"
    -   key_name: "jblack"
    -   region_id: 4
    -   image_id: 0
    -   size_id: 4
    -   private_networking: false
    -   backups_enabled: false
    -   key_path: "/home/jblack/.ssh/id_rsa"
    -   tags: {"Name"=>"testbox", "BootstrapId"=>"https://chef.linuxguru.net/nodes/testbox", "BootstrapHost"=>"comet", "BootstrapUser"=>"jblack"}
    -   flavor_name: "512MB"
    -   flavor_id: 66
    -   ssh_key_ids: [174936]
    -   name: "testbox"
    ================================================================================
    Error executing action `converge` on resource 'machine[testbox]'
    ================================================================================
    
    Excon::Errors::NotFound
    -----------------------
    Expected([200]) <=> Actual(404 Not Found)
    excon.error.response
      :body          => "{\"status\":\"ERROR\",\"error_message\":\"You specified an invalid image for Droplet creation.\",\"message\":\"You specified an invalid image for Droplet creation.\"}"
      :headers       => {
        "CF-RAY"        => "16b3082e13be11d7-SJC"
        "Cache-Control" => "no-cache"
        "Connection"    => "keep-alive"
        "Content-Type"  => "application/json; charset=utf-8"
        "Date"          => "Wed, 17 Sep 2014 05:51:26 GMT"
        "Server"        => "cloudflare-nginx"
        "Set-Cookie"    => "__cfduid=d88e2b3dafbd7571ecdd7ce6004089ea71410933086411; expires=Mon, 23-Dec-2019 23:50:00 GMT; path=/; domain=.digitalocean.com; HttpOnly"
        "Status"        => "404 Not Found"
        "X-Rack-Cache"  => "miss"
        "X-Request-Id"  => "42ec76c3d5a9c5226611f48154f82148"
        "X-Runtime"     => "0.236418"
      }
      :local_address => "192.168.2.172"
      :local_port    => 35763
      :remote_ip     => "104.16.25.4"
      :status        => 404
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/linuxguru/recipes/stack_simple.rb
    
     22: machine 'testbox' do
     23:    tag 'itsname'
     24: end
     25: 
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/linuxguru/recipes/stack_simple.rb:22:in `from_file'
    
    machine("testbox") do
      action :converge
      retries 0
      retry_delay 2
      guard_interpreter :default
      chef_server {:chef_server_url=>"https://chef.linuxguru.net", :options=>{:client_name=>"comet", :signing_key_filename=>"/etc/chef/client.pem"}}
      driver "fog:DigitalOcean"
      machine_options {:bootstrap_options=>{:image_name=>"Ubuntu 14.04 x64", :region_name=>"New York 2", :key_name=>"jblack"}}
      cookbook_name "linuxguru"
      recipe_name "stack_simple"
      attribute_modifiers [["tags", #<Proc:0x000000021ae990@/var/lib/gems/1.9.1/gems/cheffish-0.8.2/lib/cheffish.rb:149>]]
    end

Results in:
```
Running handlers:
[2014-09-16T22:51:26-07:00] ERROR: Running exception handlers
Running handlers complete
[2014-09-16T22:51:26-07:00] ERROR: Exception handlers complete
[2014-09-16T22:51:26-07:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 46.625909816 seconds
[2014-09-16T22:51:26-07:00] ERROR: machine[testbox] (linuxguru::stack_simple line 22) had an error: Excon::Errors::NotFound: Expected([200]) <=> Actual(404 Not Found)
excon.error.response
  :body          => "{\"status\":\"ERROR\",\"error_message\":\"You specified an invalid image for Droplet creation.\",\"message\":\"You specified an invalid image for Droplet creation.\"}"
  :headers       => {
    "CF-RAY"        => "16b3082e13be11d7-SJC"
    "Cache-Control" => "no-cache"
    "Connection"    => "keep-alive"
    "Content-Type"  => "application/json; charset=utf-8"
    "Date"          => "Wed, 17 Sep 2014 05:51:26 GMT"
    "Server"        => "cloudflare-nginx"
    "Set-Cookie"    => "__cfduid=d88e2b3dafbd7571ecdd7ce6004089ea71410933086411; expires=Mon, 23-Dec-2019 23:50:00 GMT; path=/; domain=.digitalocean.com; HttpOnly"
    "Status"        => "404 Not Found"
    "X-Rack-Cache"  => "miss"
    "X-Request-Id"  => "42ec76c3d5a9c5226611f48154f82148"
    "X-Runtime"     => "0.236418"
  }
  :local_address => "192.168.2.172"
  :local_port    => 35763
  :remote_ip     => "104.16.25.4"
  :status        => 404

[2014-09-16T22:51:26-07:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
root@comet
```

**Comment by jkeiser** [comment]
This should be fixed with https://github.com/chef/chef-provisioning-fog/pull/87
