### ISSUE TITLE
Fails when using with_fog_driver()

### ISSUE THREAD

**Issue by mikelococo** [chef/chef-provisioning-fog#72]
chef-provisioning works happily when using openstack configured via with_driver() as below:

```
require 'chef/provisioning'
require 'chef/provisioning/fog_driver/driver'

with_driver('fog:OpenStack',
            compute_options: {
              openstack_auth_url: "#{ENV['OS_AUTH_URL']}/tokens",
              openstack_tenant: ENV['OS_TENANT_NAME'],
              openstack_username: ENV['OS_USERNAME'],
              openstack_api_key: ENV['OS_PASSWORD']
            })
with_machine_options(bootstrap_options: {
                       image_ref: '12345',
                       flavor_ref: '12',
                       key_name: 'a-key-name'
                     })

machine 'box01' do
  action :setup
end
```

But when specifying an equivalent config via with_fog_driver() it fails:
```
with_fog_openstack_driver(compute_options: {
                            openstack_auth_url: "#{ENV['OS_AUTH_URL']}tokens",
                            openstack_tenant: ENV['OS_TENANT_NAME'],
                            openstack_username: ENV['OS_USERNAME'],
                            openstack_api_key: ENV['OS_PASSWORD']
                         })
```

The first issue is that driver is referred to by the old naming convention:
```
-        driver = Driver.from_provider(provider, config)
+        driver = Chef::Provisioning::FogDriver::Driver.from_provider(provider, config)
```

I was going to submit a PR to fix this, but it stil doesn't work. After fixing the above, the all the compute_options except for driver_url are set to nil. I would think the required fix would look like:
```
-        run_context.chef_provisioning.with_driver(driver, &block)
+        run_context.chef_provisioning.with_driver(driver, driver_options, &block)
```

But that change doesn't seem to make a difference. After quite a bit of digging, it's not clear to me what mismatch is resulting in the {driver_options: {compute_options}} settings getting niled out when the same settings work fine via with_driver.

Until a fix is found, a workaround is to specify with_driver instead of with_fog_openstack_driver

**Comment by jjasghar** [comment]
I don't think this is relevant anymore. If it is please reopen.
