### ISSUE TITLE
Add support for Google Cloud Engine (GCE)

### ISSUE THREAD

**Issue by pburkholder** [chef/chef-provisioning-fog#75]
I have work started on this at https://github.com/pburkholder/chef-provisioning-fog/tree/pdb/gce. Opening this issue here in case anyone wants to contribute to my work, as it's not yet ready for merging into this project.

**Comment by mbrukman** [comment]
What's the status of this work? @pburkholder, as you still working on this?

Is there a guide for writing support for new provisioners that one can refer to?

Also, I noticed that at least the [AWS provisioner](https://github.com/chef/chef-provisioning-aws) is written separately, rather than via Fog, "for a variety of reasons" (per the repo). What are the guidelines for choosing whether to implement a provisioner via Fog vs. separately?

Thanks for your help!

/cc: @erjohnso

**Comment by pburkholder** [comment]
I got really frustrated working with fog, so started working on a chef-provisioning-gce (modelled on chef-provisioning-aws), then realized I didn't know what I was doing, so set the work aside for a bit.

The choice of provisioner is up to you, and to whomever has the time and impetus to write them. Fog only gets you so far before you're wrestling with the inconsistent implementation of some Cloud's API -- not to blame them, it's an ambitious project. 

With aws-sdk (for the AWS provisioner) or google-api-client (GCE) you'll get behaviour that makes sense for that particular cloud, and hence it's probably easier to work with.  My $0.02.

There is no guide per se, either. The code has grown faster than the documentation around it. Probably asking for help on chef-dev mail list would be the best place to start.

**Comment by pburkholder** [comment]
This work is currently STALLED. Please feel free to poke me if you want to see it worked on again.

**Comment by kri5** [comment]
@pburkholder Do you still plan to work on chef-provisioning-gce?

**Comment by erjohnso** [comment]
@tyler-ball has started working on a GCE specific version at https://github.com/someara/chef-provisioning-google

**Comment by erjohnso** [comment]
Moved to official new home [https://github.com/chef/chef-provisioning-google].  I think this issue can be closed (although there's still a good bit of work to do on the new plugin).

**Comment by tyler-ball** [comment]
Yup - I'm going to close this in favor of what @erjohnso mentioned
