### ISSUE TITLE
Uninitialized constant ActionFailed

### ISSUE THREAD

**Issue by zambon** [chef/chef-provisioning-fog#76]
When trying to boot a server and attach a floating IP from a pool that doesn't have any IP addresses left, I get the following error from [driver.rb:453](https://github.com/opscode/chef-provisioning-fog/blob/master/lib/chef/provisioning/fog_driver/driver.rb#L453).

```shell
NameError
---------
uninitialized constant Chef::Provisioning::FogDriver::Driver::ActionFailed
```

**Comment by jkeiser** [comment]
@tyler-ball pretty sure you have a fix for this in the hopper.

**Comment by jkeiser** [comment]
I am fairly sure this is fixed by https://github.com/chef/chef-provisioning-fog/pull/86

**Comment by tyler-ball** [comment]
Correct - @zambon can you try with my branch from #86 and see if you still get the error?  If you don't, lets go ahead and close this because I'll merge that other branch soon.
