### ISSUE TITLE
Unable to set user_data when is_windows = true

### ISSUE THREAD

**Issue by xeon22** [chef/chef-provisioning-fog#83]
When the [is_windows](https://github.com/opscode/chef-provisioning-fog/blob/master/lib/chef/provisioning/fog_driver/providers/aws.rb#L134-L138) option is set to true and the driver is AWS, the user_data option is supplied by a [hard coded](https://github.com/opscode/chef-provisioning-fog/blob/master/lib/chef/provisioning/fog_driver/providers/aws.rb#L403-L421) value.

**Comment by jkeiser** [comment]
This is a reasonable ask.  Out of curiosity, what do you want to add to the user_data?

**Comment by xeon22** [comment]
Mainly to add some custom powershell to the user-data.  In this case, I wanted the ability to rename the machine to what is passed in to the machine resource.  I just figured it would be useful to be able to override what is currently defined.

**Comment by joelwilson** [comment]
:+1:  I am throwing in my support for this request as well. I ran into the hard-coded winrm per-shell memory limit (300MB) which stopped me from being able to converge a windows Jenkins slave when the recipe executed a Java which wanted to reserve 2GB of heap. It would be nice if the winrm settings were attached to some attributes and/or the user_data is settable.

**Comment by hath995** [comment]
This still seems to be an issue. I just ran into it myself.

**Comment by jjasghar** [comment]
No movement, if you'd like to help I'd love to see PR, but I'm closing this due to no movement.
