### ISSUE TITLE
AWS EC2 Windows Server 2012 R2 User Data Error

### ISSUE THREAD

**Issue by nspottsie** [chef/chef-provisioning-fog#84]
Attempting to create a Windows Server 2012 R2 instance in the us-east-1 region with ami-c4fe9aac fails

**Steps to Reproduce**
1. Create machine resource in an AWS account using AMI provided
2. Instance launches as expected
3. WinRM fails to connect, chef-client is not installed
4. Login to machine
5. Inspect meta-data to ensure that the user_data script was passed correctly: http://169.254.169.254/latest/user-data/
6. Open EC2Config log: C:\Program Files\Amazon\Ec2ConfigService\Logs\EC2ConfigLog
7. The log should contain the error message
> Ec2HandleUserData: The errors from user scripts:
Set-Content : A positional parameter cannot be found that accepts argument 
'start=auto'.
At C:\Program Files\Amazon\Ec2ConfigService\Scripts\UserScript.ps1:12 char:1
+ sc config winrm start=auto
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-Content], ParameterBin 
   dingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell 
   .Commands.SetContentCommand

**Cause**
* Line 422 in aws.rb (provider) is the source of the error: sc config winrm start=auto
* Powershell interprets sc as an alias to Set-Content instead of sc.exe

**Solution**
* I changed the command to include .exe and the error message is gone and provisioning works
: sc.exe config winrm start=auto

**Notes**
* I was able to get provisioning to work with an older version of Windows Server 2012 (ami-acf89cc4) so I suspect that the change occurred in Server 2012 R2
* My instance is a m1.large with 3 EBS volumes, so it is possible that the provisioning process was hitting the WinRm transport wait_for timeout due to the overall wait time for Amazon resources
* I tested the creation process ~10 times and was not able to successfully provision the machine until fixing the powershell error. Your mileage may vary

**Comment by jkeiser** [comment]
@fnichol you are deep in this stuff right now ... does this look at all familiar to you?

@nspottsie do you get the same issue with chef-provisioning-aws?  Now that it's up to snuff, we're starting to move to that as our permanent AWS driver instead of fog.

**Comment by joelwilson** [comment]
I am running into the same problem.

@jkeiser The problem likely exists in chef-provisioning-aws as well. It looks like a copy/paste job: [aws_driver/driver.rb](https://github.com/chef/chef-provisioning-aws/blob/ce70690391fa9d384e657b84a46a5fa49a518597/lib/chef/provisioning/aws_driver/driver.rb#L275-L288).

**Comment by nspottsie** [comment]
Unfortunately, I can't seem to get chef-provisioning-aws to create a windows machine (regardless of my bootstrap options, the driver seems to think that the machine is Linux and will try SSH instead of WinRM)

Joel is correct, the chef-provisioning-aws has the same user-data error.

I am a .NET guy, but will try to see if I can dig in here and get to source of my chef-provisioning-aws problem in order to see this through to conclusion.

**Comment by nspottsie** [comment]
The current version of chef-provisioning-aws is working for us on Windows instances now using the latest master code. Thanks for looking into this...

**Comment by joelwilson** [comment]
Please re-open this issue. The problem still exists in the chef-provisioning-fog driver. The chef-provisioning-aws [user_data](https://github.com/chef/chef-provisioning-aws/blob/master/lib/chef/provisioning/aws_driver/driver.rb#L389) is still identical to the chef-provisioning-fog [user_data](https://github.com/chef/chef-provisioning-fog/blob/master/lib/chef/provisioning/fog_driver/providers/aws.rb#L431), so I'm not sure how @nspottsie has it working there.
