### ISSUE TITLE
fog driver not working for alternative ec2_endpoint

### ISSUE THREAD

**Issue by StFS** [chef/chef-provisioning-fog#95]
I've set up a very simple test project to demonstrate this problem. It can be found at:
https://github.com/nextcode-health/qstack-chef-provisioning

I'm trying to point the fog:AWS driver to an ec2_endpoint for our local cloud cluster which is set up with QStack (https://qstack.com/) which has an EC2 compatable API. I've verified that aws-cli works against QStack so it should work with Fog as well.

However, when I point it towards our QStack EC2 endpoint I get the following error:

```
    Fog::AWS::IAM::Error
    --------------------
    InvalidClientTokenId => The security token included in the request is invalid.
```

I've investigated this a bit and it looks like Fog is still talking to the AWS IAM endpoint even though I've set the ec2_endpoint to the QStack location. I don't think QStack implements IAM though but as I said, it the aws-cli tool works fine so they are obviously authenticating users somehow. 

So I'm not quite sure how this can be solved. Can the Fog driver be instructed to not use IAM? Or is IAM the only way to authenticat against EC2 (meaning that there must be a IAM endpoint in our QStack somewhere, I just haven't found it).

**Comment by StFS** [comment]
You can see it in the project I linked to but the way I'm setting up the driver is below:

```
# The qstack in the below driver name refers to the profile name in ~/.aws/credentials
with_driver('fog:AWS:qstack', :compute_options => { 
    :ec2_endpoint => 'http://c.qstack.nextcode.local',
    #:iam_endpoint => 'http://c.qstack.nextcode.local'
})
```

**Comment by StFS** [comment]
I got some help with this from GreenQloud personnel and they figured out what was wrong and a workaround.

Basically, chef-provisioning-fog doesn't provide any way for you to skip the IAM service request.

Below is a very ugly workaround but the fog driver should make the IAM service optional.

```ruby
require 'chef/provisioning/fog_driver/driver'

server = WEBrick::HTTPServer.new :Port => 8123
trap 'INT' do server.shutdown end
server.mount_proc '/' do |req, res|
    res.body = '''
      <GetUserResponse xmlns="https://iam.amazonaws.com/doc/2010-05-08/">
        <GetUserResult>
          <User>
            <UserId>AIDACKCEVSQ6C2EXAMPLE</UserId>
            <Path>/division_abc/subdivision_xyz/</Path>
            <UserName>Bob</UserName>
            <Arn>arn:aws:iam::123456789012:user/division_abc/subdivision_xyz/Bob</Arn>
            <CreateDate>2013-10-02T17:01:44Z</CreateDate>
            <PasswordLastUsed>2014-10-10T14:37:51Z</PasswordLastUsed>
          </User>
        </GetUserResult>
        <ResponseMetadata>
          <RequestId>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestId>
        </ResponseMetadata>
      </GetUserResponse>
    '''
end
Thread.new { server.start }

# The qstack in the below driver name refers to the profile name in ~/.aws/credentials
with_driver('fog:AWS:qstack', :compute_options => {
  :endpoint => '...',
  :iam_endpoint => 'http://localhost:8123',
})
```

**Comment by tas50** [comment]
I'm going to close this out at this point since we removed support for fog-aws and instead suggest that users use fog-provisioning-aws which uses the native aws-sdk and resolves a large number of longstanding AWS issues.
